inventory_app/inventory_app/urls.py
from django.contrib import admin

from django.conf import settings
from django.urls import include, path

from . import views

handler404 = 'inventory_app.views.handler404'
handler404 = 'inventory_app.views.handler500'


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('stock_manager/', include('stock_manager.urls')),

]

"""
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
"""

inventory_app/stock_manager/urls.py
from django.urls import path, re_path

from . import views

app_name='stock_manager'

urlpatterns = [
    path('', views.index, name='index'),
    
    re_path(r'^shop/(?P<id>[0-9]+)$', views.show, name='show'),
    path('shop/add/', views.ShopCreate.as_view(), name='shop-add'),
    path('shop/<int:pk>/', views.ShopUpdate.as_view(), name='shop-update'),
    path('shop/<int:pk>/delete/',  views.ShopDelete.as_view(), name='shop-delete'),

    re_path(r'^StockReading/(?P<id>[0-9]+)$', views.sreading, name='sreading'),


]


"""
#    path('product/add/', views.ProductCreate.as_view(), name='product-add'),
    re_path(r'^product/(?P<id>[0-9]+)$/add/', views.ProductCreate.as_view(), name='product-add'),
    path('product/<int:pk>/', views.ProductUpdate.as_view(), name='product-update'),
    path('product/<int:pk>/delete/',  views.ProductDelete.as_view(), name='product-delete'),
"""

inventory_app/stock_manager/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinLengthValidator

# Create your models here.

class TimestamptedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True
        

class Shop(TimestamptedModel):
    name    = models.CharField(max_length=255, unique=True)
    owner   = models.CharField(max_length=255, default="BigBoss")
    address = models.TextField()

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('stock_manager:show', kwargs={'id': self.id})


class Product(TimestamptedModel):
    name      = models.CharField(max_length=255, unique=True)
    reference = models.CharField(max_length=13, validators=[MinLengthValidator(13)], unique=True)
    shop   = models.ForeignKey(Shop, on_delete=models.CASCADE)
    expiry_date = models.DateTimeField()

    class Meta:
        ordering = ['expiry_date']

#    def get_absolute_url(self):
#        return reverse('stock_manager:show', kwargs={'id': self.id})


class StockReading(TimestamptedModel):
    
    shop     = models.ForeignKey(Shop, on_delete=models.CASCADE)
    product  = models.ForeignKey(Product, on_delete=models.CASCADE)
    nb_prev  = models.IntegerField()

    def __str__(self):
        return "ref={}, DLV = {}".format(self.product.reference, self.product.expiry_date)

inventory_app/stock_manager/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass

inventory_app/inventory_app/views.py
from django.shortcuts import render

from django.http import HttpResponse

def home(request):
    return render(request, 'pages/home.html')
#    return HttpResponse('<h1>Hello World</h1>')

def about(request):
    return render(request, 'pages/about.html')

def contact(request):
    return render(request, 'pages/contact.html')

def handler404(request, exception):
    return render(request, 'errors/404.html', {'error': exception}, status=404)

def handler500(request, exception=None):
    return render(request, 'errors/500.html', {'error': exception}, status=500)

inventory_app/stock_manager/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView

from .models import Shop, Product, StockReading

import datetime

# Create your views here.


def index(request):
    shops = Shop.objects.all()

    return render(request, 'stock_manager/index.html', {'shops': shops})


def show(request, id):
    shop = get_object_or_404(Shop, pk=id)
    products = Product.objects.filter(shop__pk=id)
    stockreadings = []

    if len(products) > 0:
        for product in products:

            nb_prev = len(StockReading.objects.filter(product__pk=product.id)) + 1
            stockreadings.append(StockReading(shop = shop, product = product, nb_prev = nb_prev))
            stockreadings[-1].save()
    return render(request, 'stock_manager/shop.html', {'shop': shop, 'products': products, 'stockreadings':stockreadings})

def sreading(request, id):
    stockreadings = StockReading.objects.filter(product__pk=id)
    if len(stockreadings)>0:
        sname = stockreadings[0].shop.name
        pname = stockreadings[0].product.name
        rid   = stockreadings[0].product.reference
        dlv   = stockreadings[0].product.expiry_date

        return render(request, 'stock_manager/sreading.html', {'stockreadings': stockreadings, 'sname':sname, 'pname': pname, 'rid': rid, 'dlv': dlv})


class ShopCreate(CreateView):
    model = Shop
    fields = ['name', 'owner', 'address']

class ShopUpdate(UpdateView):
    model = Shop
    fields = ['name', 'owner', 'address']

class ShopDelete(DeleteView):
    model = Shop
    success_url = reverse_lazy('stock_manager:index')

"""
class ProductCreate(CreateView):
    model = Product
    fields = ['name', 'reference', 'expiry_date']

    def form_valid(self, form):
        form.instance.shop_id = self.request.shop.id 
        return super().form_valid(form)
    



class ProductUpdate(UpdateView):
    model = Product
    fields = ['name', 'reference', 'expiry_date']


class ProductDelete(DeleteView):
    model = Product
    success_url = reverse_lazy('stock_manager:index')
"""

inventory_app/stock_manager/templates/stock_manager/index.html
{% extends 'layouts/base.html' %}

{% block title %}Stock Manager{%endblock%}

{% block content %}

<h1>Shop List : {{ shops|length }} shops managed</h1>

{% for shop in shops %}
    <article>
        <h2><a href ="{% url 'stock_manager:show' id=shop.id %}">#{{ shop.id }} - {{ shop.name|upper }}</a></h2>
	<p>Owner : {{ shop.owner }}</p>
	<p>Address : {{ shop.address }}</p>

	 <p><a href="{% url 'stock_manager:show' id=shop.id  %}">Go to the products management</a></p>

    </article>

    {% if not forloop.last %}
        <hr>
    {% endif %}

{% empty %}
    <p>No Shops yet</p>

{% endfor%}

{% endblock %}

inventory_app/stock_manager/templates/stock_manager/product_form.html
{% extends 'layouts/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save product</button>
  </form>
{% endblock %}

inventory_app/stock_manager/templates/stock_manager/shop.html
{% extends 'layouts/base.html' %}

{% block title %}Shop | {{ shop.name }}{%endblock%}

{% block content %}
<p><a href="{% url 'stock_manager:index' %}">Bask to shop list</a></p>

<article>

	<h2>StockReadings of this session:</h2>
	{% for stockreading in stockreadings %}
        <article>
		<h3>StockReading #{{ stockreading.nb_prev }} for : {{ stockreading.product.name }}</h3>
		<p>DLV : {{ stockreading.product.expiry_date }}</p>
		<p>Click <a href="{% url 'stock_manager:sreading' id=stockreading.product.id %}">here</a> to see StockReading history</p>
	</article>
	{% empty %}
            <p>No products yet</p>
        {% endfor%}



</article>



<article>
	<h2>Name : {{ shop.name }}</h2>
	<p>Owner : {{ shop.owner }}</p>
	<p>Address : {{shop.address }}</p>

	<hr>
	<h2>{{ products|length }} Products :</h2>
	
	{% for product in products %}
	<article>
	    <p>Name : {{ product.name  }}</p>
	    <p>Reference : {{ product.reference }}</p>
	    <p>DLV : {{ product.expiry_date }}</p>

        </article>


        {% if not forloop.last %}
            <hr>
        {% endif %}

        {% empty %}
            <p>No products yet</p>
	{% endfor%}

</article>

{% endblock %}

inventory_app/stock_manager/templates/stock_manager/shop_confirm_delete.html
{% extends 'layouts/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Delete Shop </button>
  </form>
{% endblock %}

inventory_app/stock_manager/templates/stock_manager/shop_form.html
{% extends 'layouts/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save shop</button>
  </form>
{% endblock %}

inventory_app/stock_manager/templates/stock_manager/sreading.html
{% extends 'layouts/base.html' %}

{% block title %}StockReading History{%endblock%}

{% block content %}

<h1>All StockReadings of this product</h1>
<p>Shop name {{ sname  }}</p>
<p>Product name : {{ pname }}</p>
<p>last reference id : {{ rid }}</p>
<p>DLV : {{ dlv }}</p>
<hr>
{% for stockreading in stockreadings %}
    <article>
	    <p>Creation : {{ stockreading.created_at }}</p>
	    <p>Number : {{ stockreading.nb_prev }}</p>
	    </article>

    {% if not forloop.last %}
        <hr>
    {% endif %}

{% empty %}
    <p>No StockReading, strange</p>

{% endfor%}

{% endblock %}

inventory_app/templates/layouts/_footer.html
<footer>

	<p>&copy; Copyright {% now 'Y' %} &middot; Lf-connection &middot; All rights reserved</p>
</footer>

inventory_app/templates/layouts/_nav.html
<nav class="navbar">
	<a href="#" class="navbar-brand">CB+</a>
	<ul class="navbar-right">
		<li><a href="{% url 'home' %}">Home</a></li>
		<li><a href="{% url 'stock_manager:index' %}">stock_manager</a></li>
		<li><a href="{% url 'about' %}">About</a></li>
		<li><a href="{% url 'contact' %}">Contact</a></li>
	</ul>
</nav>

inventory_app/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<title>{% block title %}Inventory App{%endblock%} </title>
	</head>
	<body>
		{% include 'layouts/_nav.html' %}
		<div class="container">
			<div class="col-8">
				{% block content %}{% endblock %}
			</div>
		</div>
		{% include 'layouts/_footer.html' %}
	</body>
</html>

inventory_app/templates/layouts/blank.html
{% extends 'layouts/base.html' %}

{% block title %}{%endblock%}

{% block content %}



{% endblock %}

inventory_app/templates/pages/about.html
{% extends 'layouts/base.html' %}

{% block content %}

    <h1>About</h1>

{% endblock %}

inventory_app/templates/pages/contact.html
{% extends 'layouts/base.html' %}

{% block content %}

<h1>contact</h1>

{% endblock %}

inventory_app/templates/pages/home.html
{% extends 'layouts/base.html' %}
{% load i18n %}

{% block title %}Home page{%endblock%}

{% block content %}

<h1>{% trans "Hello Owners" %}</h1>

    <p>Trouvez votre <a href="{% url 'stock_manager:index' %}">shop</a></p>

{% endblock %}